### ISSUE TITLE
Lua Install for Mac - Steam and Permissions issues

### ISSUE THREAD

**Issue by SaveTheJohnDoe** [evilfactory/LuaCsForBarotrauma#107]
Hello,

Thanks for the work on Lua for Baro, it's great stuff. I have no issues at all on my Windows but getting a fair bit of small troubles on my Mac (laptop for when I'm away from my main pc). I have an issue with steam not being picked-up. Not sure where to find the steam client.so binary in my steam install, however.

Guide states for Linux machines: "Sometimes you will get steam initialization errors, most of the time it's because it's missing the linux64/steamclient.so binary, so you can just copy the binary from your steam installation over to the folder and it should work."

Screenshot of steam issue: [https://cdn.discordapp.com/attachments/614212649571581973/1015948603396730912/Screenshot_2022-09-04_at_12.36.38_PM.png](https://cdn.discordapp.com/attachments/614212649571581973/1015948603396730912/Screenshot_2022-09-04_at_12.36.38_PM.png)

I also had a tedious however solvable issue with Mac flagging every single executable as dangerous and requiring manual allowance - if there's a way to automate that, would be nice to include it in the guide. It's very streamlined for linux and windows users but it does skip a few steps for Mac users (e.g. 2 Contents folders within the barotrauma.app, I copied both but bit of a gamble).

Screenshot of permissions (verified each single file manually, about 50 total? Probably a bit more. All executables and dlls basically. [https://cdn.discordapp.com/attachments/614212649571581973/1015947969666756608/Screenshot_2022-09-04_at_12.18.56_PM.png](https://cdn.discordapp.com/attachments/614212649571581973/1015947969666756608/Screenshot_2022-09-04_at_12.18.56_PM.png)

Anything else you need please let me know.

**Comment by evilfactory** [comment]
I see you did the installation from scratch, you could try doing the installing to an existing client/server instead, someone else had the same issue, and this one worked for them without problems.

**Comment by SaveTheJohnDoe** [comment]
Update: Mac barotrauma_lua folder needs at least an extra 2 files as follows:
- steamclient.dylib located at /Users/damienpoblete/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS
- steam_appid.txt which needs to be created as a plain text file, and only contain the text 255710 (https://steamcommunity.com/app/255710/discussions/0/611701360827397212/)
However it doesn't seem to see my subscribed mods and struggles finding some other steam files.

As I'm typing this just read your reply. I'll give that a try instead and let you know if it works, and close this thread accordingly. Perhaps guide can make it explicit that Mac users shouldn't do from scratch (unless done as above and still a few issues to sort-out for a full manual install haha)

**Comment by SaveTheJohnDoe** [comment]
> I see you did the installation from scratch, you could try doing the installing to an existing client/server instead, someone else had the same issue, and this one worked for them without problems.

Can confirm, the "Adding to an existing client" install is the way to go for Mac users. Lua now works, cheers.
