### ISSUE TITLE
Finding specific components with signalReceived

### ISSUE THREAD

**Issue by Herbalicious** [evilfactory/LuaCsForBarotrauma#118]
I'm attempting to create a signal component that needs to store information specific to itself. I am using the `signalReceived.myComponent` hook, but to my understanding local variables are not persistent between calls. I've made a working version of what I want using global variables, but that limits me to a single active component due to interference.

I've looked though all of the examples and documentation to try to find a solution but I struggle to make sense of a lot of it since I'm very rusty with Lua. Is there an existing way to achieve this? If not, would it be possible to add a parameter to `signalReceived.myComponent` that outputs the specific component which received the signal that triggered the hook?

**Comment by evilfactory** [comment]
Signals aren't tied to a specific component. 
I don't get what limits you to a single component, you can just use a table that has the items as keys and then some data that you want to store, as shown in this example https://github.com/evilfactory/Misc-Barotrauma-Lua-Scripts/blob/main/LuaExamples/Lua/Autorun/advancedcustomwiring.lua

**Comment by Herbalicious** [comment]
I _thought_ I was missing something in the advanced wiring example. `connection.Item` was exactly what I needed, thank you!
