### ISSUE TITLE
Hook "think" is called twice per tick.

### ISSUE THREAD

**Issue by zhu-rengong** [evilfactory/LuaCsForBarotrauma#120]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

https://github.com/evilfactory/LuaCsForBarotrauma/blob/fe2d0bdddb8061910256ffdc97531586be8dd502/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs#L351-L352

https://github.com/evilfactory/LuaCsForBarotrauma/blob/fe2d0bdddb8061910256ffdc97531586be8dd502/Barotrauma/BarotraumaShared/SharedSource/LuaCs/LuaCsSetup.cs#L199-L204

### Bug prevalence

Happens every now and then

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by evilfactory** [comment]
Fixed in 335b16c
