### ISSUE TITLE
LuaCs isn't initialized when using the "quickstart" command to start a game

### ISSUE THREAD

**Issue by KilianKilmister** [evilfactory/LuaCsForBarotrauma#121]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Happens when using a C# mod. I haven't checked whether this happens for lua specifically as well, but I'm assuming it does, because there's no init-message in the debug console. I found one mention about [looking into `quickstar`][com-a] in  #40, and something related having been [fixed in unstable][com-b], but I wasn't able to find what code change that referred to exactly.

[com-a]:<https://github.com/evilfactory/LuaCsForBarotrauma/issues/40#issuecomment-1090932293>
[com-b]:<https://github.com/evilfactory/LuaCsForBarotrauma/issues/40#issuecomment-1094380459>

### Reproduction steps

1. Enable any C# mod.
2. Use the `quickstart` command in the main menu.

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by evilfactory** [comment]
It's possible to manually initialize the mod by running the console command `reloadluacs`. 
While quickstart doesn't automatically initialize the mod, i think that behavior is useful for testing, though i can always create a separate command for it.
