### ISSUE TITLE
Question regarding C# mods and classes added by LuaCs

### ISSUE THREAD

**Issue by KilianKilmister** [evilfactory/LuaCsForBarotrauma#122]
**Now this is potentially a really stupid question, but to create a C# mod for LuaCs, is it actually necessary to actively use any of the classes LuaCs provides for mods to use?**
I only realized it after I was basically finished with writing my first proper C# mod for the game that it didn't use LuaCs classes like `ACsMod`. As far as I can tell, that mod is fully functional on both client and server. So I'm basically wondering if there's something I'm missing.

Quoting the LuaCs docs:
> The main star of the show is [Barotrauma::ACsMod](https://evilfactory.github.io/LuaCsForBarotrauma/cs-docs/baro-server/html/class_barotrauma_1_1_a_cs_mod.html) class. It is what all your mods will use to hook game methods, and execute custom code.

I originally took this to mean any C# mod was basically bound to using `ACsMod`, but now I'm wondering if that should be taken more literally, and less-invasive mods will get by just fine without it.

[Link to mod repo in case anybody want's to see how it's implemented or what the mod does (readme etc. is included).](https://github.com/KilianKilmister/BaroMod-RouterComponent)

In this mod I just implemented another `ItemComponent` in the same way builtin ones are, and implemented in XML that new component in also newly created items. This seems to work; LuaCs loads the code, and the game will use its content using the exact same functionality it uses vanilla content.
This shouldn't be taken as a complaint. On the contrary, being able to do it like that is downright lovely. Just looking whether somebody is able to shed a little light on the matter.

**Comment by evilfactory** [comment]
It's not required, it's just used as an entry point of your mod, where you usually will define any harmony patches.
