### ISSUE TITLE
afflictionUpdate hook does not support singleplayer.

### ISSUE THREAD

**Issue by Herbalicious** [evilfactory/LuaCsForBarotrauma#157]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm attempting to write a hook using `afflictionUpdate`, and primarily code in the sub editor. However, the hook doesn't work here as the submarine editor is considered singleplayer, and the hook appears to only be called on the server.

### Reproduction steps

1. Create a new lua hook using `afflictionUpdate`
```lua
Hook.Add("afflictionUpdate", "experiment", function(affliction, characterHealth, limb)
    print("Affliction Update: ", affliction.Identifier)
end)
```
2. Save and load into submarine editor or singleplayer.
3. Use a command to apply an affliction to yourself, eg. `giveaffliction vigor 100 <charactername>`.
4. Observe that nothing appears in the console.
5. Exit, then host a multiplayer game.
6. Repeat step 3.
7. Observe that the message appears in the console.

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by evilfactory** [comment]
Old remanence of when this mod was server-side only, fixed on a58cb82
