### ISSUE TITLE
item.equip and item.unequip hooks are inconsistent with each other.

### ISSUE THREAD

**Issue by Herbalicious** [evilfactory/LuaCsForBarotrauma#158]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The item.equip hook triggers on clothing equip, but the item.unequip hook does not.
For example, equipping an outfit or headgear will call item.equip, but taking them off does not call item.unequip.

### Reproduction steps

1. Write an item.equip and item.unequip hook.
```lua
Hook.Add("item.equip", "test1", function(item, character)
	print("Item Equipped")
end)

Hook.Add("item.unequip", "test2", function(item, character)
	print("Item Unequipped")
end)
```
2. Load into a game and equip/unequip any clothing or headgear.
3. Observe that "Item Equipped" is the only message appearing in console.
3b. ("Item Unequipped" message will still appear for unequipping an item from your hands, eg. Captain's Revolver)

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by evilfactory** [comment]
I'm afraid this is an inconsistency with Barotrauma itself, we are just hooking into the methods Item.Equip and Item.Unequip present in the game, so any behavior comes from that.
