### ISSUE TITLE
Can't install on linux: `tried to register a type that doesn't exist Barotrauma.AITrigger`

### ISSUE THREAD

**Issue by nmay231** [evilfactory/LuaCsForBarotrauma#159]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Note, I was able to easily install Lua for Barotrauma a couple of months ago, but can no longer. None of the other mods load correctly because of the error: `tried to register a type that doesn't exist Barotrauma.AITrigger`

To prevent weird issues, I completely reinstalled barotrauma, only enabled this mod, and followed the install instructions for the Windows version. There were no errors during the installation. After opening a new vanilla lobby to test if it installed correctly, I get the following error:

![Screenshot from 2023-10-01 13-03-50](https://github.com/evilfactory/LuaCsForBarotrauma/assets/35386821/a5baa697-582d-4cc1-8b4c-72cec7bb2573)

Following the common troubleshooting listed on the workshop page didn't resolve the issue for me.

### Reproduction steps

1. Launch the freshly installed barotrauma
2. Enable the Lua for Barotrauma Linux mod
3. Host a server using the modded executable
4. In the server, run `install_cl_lua`
5. Restart
6. Open a vanilla lobby
7. See error message listed.

### Bug prevalence

Happens every time I play

### Version

Other

### -

v1.0.20.1

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

The last crash report was made in May 2023, so it's not even relevant.

**Comment by nmay231** [comment]
I am willing to try to build the latest version of the project if that'll help. I haven't worked with Csharp but It'd be interesting.

**Comment by evilfactory** [comment]
Delete the `Lua` folder located in your game files, or go to LuaCs Settings and enable "Prefer Workshop Lua Folder"

**Comment by nmay231** [comment]
Deleting the Lua directory worked, thanks! (`~/.local/share/Steam/steamapps/common/Barotrauma/Lua`)
