### ISSUE TITLE
HideAndDisable function does not work when ran server-side.

### ISSUE THREAD

**Issue by Herbalicious** [evilfactory/LuaCsForBarotrauma#169]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

`limb.HideAndDisable` and `character.AnimController.HideAndDisable` only works in singleplayer.
Upsettingly, unless I'm just stupid, I get the feeling this is probably an upstream issue. 😞

### Reproduction steps

1. Write a script utilizing a `.HideAndDisable` function, eg:
```
Hook.Add("item.equip", "a", function(item, character)
	local huskAppendages = {}
        for limb in character.AnimController.Limbs do
            if string.find(tostring(limb.Name), "Huskappendage %d+") then
                table.insert(huskAppendages, limb)
            end
        end
	for limb in huskAppendages do 
                -- (Enable one of these at a time to test them, obviously)
		limb.HideAndDisable(0, false)
		-- character.AnimController.HideAndDisable(limb.type, 0, false)
	end
end)
```
2. Make a sub in the editor. (In this case you might want husk genes and a splicer so you're not racing it.)
3. With client Lua enabled, test.
    3a. Give yourself husk with `giveaffliction huskinfection 74`.
    3b. Wait for the husk appendage to appear. 
    3c. (Optional) Insert the husk genes, so you don't seize and die.
    3d. Equip any item.
4. Observe that the appendage disappears.
5. Quit out of the sub builder and host a server, repeating the above steps.
    5a. If needed: `enablecheats`, `spawnitem geneticmaterialhusk cursor`, `spawnitem genesplicer cursor`
7. Observe that the appendage does not disappear.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by evilfactory** [comment]
Well as you have guessed, this is just a direct binding to a method in barotrauma itself. You will probably need to use networking or something to tell the clients to call this method, since the method is probably supposed to be called on both realms to sync properly.
