### ISSUE TITLE
Serverside LUA errors show mod pathing, potentially leaking private information

### ISSUE THREAD

**Issue by WrillWasTaken** [evilfactory/LuaCsForBarotrauma#175]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Errors in the debug console show the mod's pathing to the entire server in multiplayer. On windows servers hosted from the in-game menu, this means any workshop mods will show the name of the user. Which may contain real names. Mine for example, contains my full real name.

![image](https://github.com/evilfactory/LuaCsForBarotrauma/assets/86113712/27d3e21c-3445-42c2-aa55-4aaca20d1874)
_Name covered up... for obvious reasons._

### Reproduction steps

Host a server from the in-game menu.
Cause a LUA error in the debug console.
Have another server member read the debug console.
They now know the host's windows username.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by WrillWasTaken** [comment]
I'm not sure if this is technically a "bug", in the sense that something doesn't work as intended, but it seems like a somewhat severe issue to me.

**Comment by evilfactory** [comment]
Would an option to only send LuaCs logs to the server host solve this issue?

**Comment by WrillWasTaken** [comment]
I would presume so. I doubt it's an issue if the host knows their own username.

**Comment by evilfactory** [comment]
Fixed in c7b8cda
