### ISSUE TITLE
Hiding usernames in error logs doesn't work

### ISSUE THREAD

**Issue by WrillWasTaken** [evilfactory/LuaCsForBarotrauma#180]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Username is visible despite "Hide Usernames In Error Logs" being enabled.
![image](https://github.com/evilfactory/LuaCsForBarotrauma/assets/86113712/e502f455-528d-42d2-93f7-90b29a0d3951)

### Reproduction steps

1, Encounter an error.
2. Read the error.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by evilfactory** [comment]
Tested myself, couldn't reproduce 
![Barotrauma_k0sYlvWAUY](https://github.com/evilfactory/LuaCsForBarotrauma/assets/36804725/4320b970-cd2b-4952-91ca-aa2b6e219c32)
