### ISSUE TITLE
Can't create issues

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [evilfactory/LuaCsForBarotrauma#220]
Barotrauma "new issue" button is redirecting you to baro discussions
So does "new issue" button in luatrauma repo
![BaroDev (wide)](https://github.com/user-attachments/assets/e8b50714-9e98-4fdd-8bf3-b99b73cb7096)

**Comment by evilfactory** [comment]
guh

**Comment by evilfactory** [comment]
#911fff1
