### ISSUE TITLE
Husk transformation causes much more lags in luatrauma than in base game

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [evilfactory/LuaCsForBarotrauma#221]
### Disclaimers  

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

10 simultaneously transforming patients
in luatrauma:
![20240906054104_1](https://github.com/user-attachments/assets/65ee29e5-a38e-459c-97a8-6fb7cc5a228b)
In base game
![20240906054651_1](https://github.com/user-attachments/assets/1f4d1686-19a5-48eb-9a88-eb45d175e508)

### Reproduction steps

- Take [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=3286179963)
- open any sub anywhere, e.g. "A test chamber" in sub editor
- triggerevent "husk lag"

it will spawn 10 patients with 99% husk infection on main sub

Or 

just give random people 100% husk infection

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

luatrauma v1.5.9.2 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by evilfactory** [comment]
Fixed in 307c81c, seems like this thing is called so many times per second when the husk transformation is happening, wouldn't doubt this could lag even in vanilla if amplified more.
