### ISSUE TITLE
FieldAccessException when trying to access events in other classes

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [evilfactory/LuaCsForBarotrauma#223]
### What happened?
E.g. this simple "in memory" mod

```
using System;
using System.Reflection;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

using Barotrauma;
using HarmonyLib;
using Microsoft.Xna.Framework;

// this doesn't help
using System.Runtime.CompilerServices;
[assembly: IgnoresAccessChecksTo("Barotrauma")]
[assembly: IgnoresAccessChecksTo("DedicatedServer")]
[assembly: IgnoresAccessChecksTo("BarotraumaCore")]

namespace Cursed
{
  public partial class OtherClass
  {
    public event Action CursedEvent;
    public Action ChadDelegate;
  }

  public partial class Mod : IAssemblyPlugin
  {
    public event Action ChadEventInMainMod;
    public OtherClass otherObject;

    public void Initialize()
    {
      otherObject = new OtherClass();

      otherObject.CursedEvent += () => log("so cursed");
      otherObject.ChadDelegate = () => log("ChadDelegate");

      ChadEventInMainMod += () => log("ChadEventInMainMod");

      try
      {
        ChadEventInMainMod?.Invoke();
        otherObject.ChadDelegate?.Invoke();
        otherObject.CursedEvent?.Invoke();
      }
      catch (Exception e) { log(e, Color.Yellow); }
    }

    public static void log(object msg, Color? cl = null)
    {
      cl ??= Color.Cyan;
      LuaCsLogger.LogMessage($"{msg ?? "null"}", cl * 0.8f, cl);
    }

    public void OnLoadCompleted() { }
    public void PreInitPatching() { }

    public void Dispose() { }
  }
}
```
Yields this
![Screenshot_7](https://github.com/user-attachments/assets/a0a00316-eb0a-42f0-a25c-088deb496380)

Is it easy to fix or is it easier to just write my own implementation of c# events?
![barodev small](https://github.com/user-attachments/assets/d2590d72-32ee-4e41-a8ac-1ddec90483f6)

### Reproduction steps
https://steamcommunity.com/sharedfiles/filedetails/?id=3331683358

**Comment by MapleWheels** [comment]
This is not a bug, you cannot invoke an event from outside the declaring hierarchy: 

Make a wrapper method in OtherClass that invokes the event and call that instead.

The keyword 'event' in C# just creates and exposes an Observable for that delegate. The actual field is protected. This is similar to how Properties work (compiler generates a hidden backing field for the property).

I'll reopen the issue if the error persists.

![Screenshot_20240915_141917_Samsung Internet](https://github.com/user-attachments/assets/0a7f7f48-6b14-4800-b6d5-174c63c2c035)

**Comment by SomeRandomNoobKekeke** [comment]
It works
![Screenshot_8](https://github.com/user-attachments/assets/fa5d6d26-77e8-4880-bf38-0a0390dbac7c)
But now i don't know what's uglier: those wrappers around every event or my implementation
