### ISSUE TITLE
Any "in memory" C# mod with server or shared code throws "An assembly with the same simple name 'DedicatedServer' has already been imported"

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [evilfactory/LuaCsForBarotrauma#239]
I've tried reinstalling the game, didn't help
![Screenshot_2](https://github.com/user-attachments/assets/b13baa10-e8ff-48c1-aa2e-31f893f6152e)
Meanwhile the mod:
![Screenshot_3](https://github.com/user-attachments/assets/a2baf1dc-292b-4e55-9a33-7920f8ea6a3a)
https://steamcommunity.com/sharedfiles/filedetails/?id=3356544346
![Screenshot_4](https://github.com/user-attachments/assets/4ae4afba-4988-4b96-8f7b-cbfcc7ec0c75)

**Comment by SomeRandomNoobKekeke** [comment]
guh...

**Comment by SomeRandomNoobKekeke** [comment]
I just deleted baro folder, reinstalled the game and copy pasted patches from latest release
![barodev small](https://github.com/user-attachments/assets/cb681120-b419-4ea8-ac68-e5094f9eeed9)

**Comment by evilfactory** [comment]
Compare the versions of DedicatedServer.dll and DedicatedServer.dll from the publicized folder

**Comment by SomeRandomNoobKekeke** [comment]
Well, dll's are different, not sure how to get the version

**Comment by evilfactory** [comment]
Right click, properties, metadata section

**Comment by SomeRandomNoobKekeke** [comment]
hmm
![Screenshot_1](https://github.com/user-attachments/assets/99865759-e009-48e9-8bfd-2a2f2e5d7f89)

**Comment by evilfactory** [comment]
Are you using the content package version of the mod?

**Comment by SomeRandomNoobKekeke** [comment]
no, i copy paste patches from releases

**Comment by SomeRandomNoobKekeke** [comment]
Weird, and now it just works with both install ways
The only difference was that i had outdated lua mod lying in workshop folder
I updated it and now issue is gone
Hmm, i have "prefer to use workshop lua" unchecked, weird

**Comment by SomeRandomNoobKekeke** [comment]
yes

**Comment by evilfactory** [comment]
Fixed in 6ab0e7b
