### ISSUE TITLE
Barotrauma.Particles is not accessable through Lua

### ISSUE THREAD

**Issue by FamiliarBreakfast** [evilfactory/LuaCsForBarotrauma#242]
I'm working on a mod that handles large amounts of particles, and it would be nice to be able to render them clientside. Since both the `Particle` and `ParticleManager` classes are under the `Barotrauma.Particles` namespace, this seems to be impossible through just lua scripting.

**Comment by Ydrec** [comment]
They are registered by default but dont  have static created

You can just make static accessors for them yourself or get already existing instances of them as fields from other statics

```
Particle = LuaUserData.CreateStatic('Barotrauma.Particles.Particle', true)
ParticleManager = LuaUserData.CreateStatic('Barotrauma.Particles.ParticleManager', false)
ParticlePrefab= LuaUserData.CreateStatic('Barotrauma.Particles.ParticlePrefab', false)
```
or
```
Game.ParticleManager
Particle = Game.ParticleManager.CreateParticle(ParticlePrefab prefab, Vector2 position, Vector2 velocity, float rotation = 0f, Hull hullGuess = null, ParticleDrawOrder drawOrder = ParticleDrawOrder.Default, float collisionIgnoreTimer = 0f, float lifeTimeMultiplier = 1f, Tuple<Vector2, Vector2> tracerPoints = null)
ParticlePrefab = Game.ParticleManager.FindPrefab(string prefabname)
```
