### ISSUE TITLE
Server restart drops all custom command permissions

### ISSUE THREAD

**Issue by Qowyn** [evilfactory/LuaCsForBarotrauma#46]
The server is loading it's settings and thus client permissions inside the GameServer constructor, but the lua setup script runs after that. This causes all command permissions of commands added by lua to be lost, since they have to be defined before loading the client permission file.

**Comment by Qowyn** [comment]
Bug can be worked around by manually calling Game.ServerSettings.LoadClientPermissions() after commands have been redefined, but this won't prevent errors from getting logged during server start.

**Comment by evilfactory** [comment]
Any suggestion for what should be done to fix this? I can make it only load permissions after all scripts have been executed, but i feel like this could break something.
