### ISSUE TITLE
Barotrauama disconnects on map change

### ISSUE THREAD

**Issue by EnderMalk** [evilfactory/LuaCsForBarotrauma#83]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Upon map change, Barotrauma will desync and disconnect clients. Both host and client are using the same mods

### Reproduction steps

1. start a multiplayer campaign
2. trigger a map change 
3. client will be disconnected
4. to fix, client will have to restart game to be able to reconnect, as server will reject reconnects

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by EnderMalk** [comment]
It's only causing a disconnect with lua for barotrauma + performance optimization installed. Otherwise, it works fine

**Comment by evilfactory** [comment]
https://github.com/Regalis11/Barotrauma/issues/8953
