### ISSUE TITLE
Start server error after manual installation of luamod

### ISSUE THREAD

**Issue by fatinghenji** [evilfactory/LuaCsForBarotrauma#89]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

![94V7MRMN)5XA%`O `8K6@8](https://user-images.githubusercontent.com/37131177/169587160-252cc02d-9fd4-4f00-b21f-316f9aeddf94.png)
Start server error after manual installation of luamod
Unable to connect to the game server

### Reproduction steps

![94V7MRMN)5XA%`O `8K6@8](https://user-images.githubusercontent.com/37131177/169587160-252cc02d-9fd4-4f00-b21f-316f9aeddf94.png)
Start server error after manual installation of luamod

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Coroutine Barotrauma.Networking.GameServer+<StartServer>d_54 threw an exception: InitCameSerer returned false (0,46593,27015,0,NoAuthentication,"1.0.0.0")
  at Steamworks.SteamServer.Init(AppId appid, SteamServerInit init,Boolean asyncCalbacks)inE:\Barotrauma-development \Libraries Facepunch.Steamworks\SteamServer.cs:line 93
  at Barotrauma.Steam.SteamManager.CreateServer GameServer server，Poolean isPublic) in<DEP>/Barotrauma/BarotraumaServer/ServerSource/Steam/SteamManager.cs:line 23
  at Barotrauma.Networking.GameServer.StartServer Boolean isPublic)+MoveNext ( in 〈DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 201
  at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in DEV>/ Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 196
  at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs :line 229
```

**Comment by evilfactory** [comment]
Can you show the rest of the console logs?

**Comment by fatinghenji** [comment]
I'm afraid that's all the output

**Comment by evilfactory** [comment]
You should be able to scroll up, here's how mine looks like:
(start of the logs)
![image](https://user-images.githubusercontent.com/36804725/169588635-4ac51d10-99ba-4ced-ad97-8650bdff92f5.png)

**Comment by fatinghenji** [comment]
![PHN75~_00(N~D06} }C_M0R](https://user-images.githubusercontent.com/37131177/169589917-32b018bd-d37d-4abc-bfca-030846c8d2f0.png)

**Comment by evilfactory** [comment]
Weird... The error happens because it's unable to initialize steam, does this also happen on vanilla dedicated servers?

**Comment by fatinghenji** [comment]
This problem appeared only after the files were replaced manually. It did not appear on the original server.

**Comment by fatinghenji** [comment]
Use the `app_update 602960 validate` command to download the application that should be in demand for the steam version.
Changing to the `app_update 102630 validate` command will not cause this problem.
The reason for this problem should be because I don't have the steam client installed on my server, thus causing the problem.
