### ISSUE TITLE
Mods not requiring Server side are not showing up in the server mod's list

### ISSUE THREAD

**Issue by theCrius** [evilfactory/LuaCsForBarotrauma#94]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

This is a replica of an issue just opened on Regalis11 repo for barotrauma. Ref link is down after this opening message. Please check his reply for further testing.

------------

We need someone else to further investigate this to be sure it's not just a problem I'm running into with my configuration.
This is the docker image I've been using, built by myself using another as a starting point: https://github.com/theCrius/barotrauma-docker

I've been running a dedicated server for several months now, since the release of the mod's refactor in Barotrauma really.

The behaviour that I keep seeing consistently is this:

- If a mod requires it to be installed server side to be able to function on a dedicated server, it will show up and work as expected (provided the mod doesn't have bugs itself). With working as intended I mean that it shows up in the server's mods' list and who connect can download it from the server if not already subscribed to the mod.

- If a mod **does not** requires to be installed on the server, even if installed (mod's file in the right directory and `config_player.xml` edited to include it) it will not show up in the server's mods' list.

Now this second case would be fine as if a mod's not requiring a server side, doesn't matter if it's visible or not.
However, unfortunately, when connecting to a server, the clients are forced to have the exact same list of mods running which means that mods that are meant to work just client's side will be disabled as they are not in the server's mods' list.

### Reproduction steps

- If possible, deploy a fresh VM, if not, at least create a new user to be sure to have a clean-ish system
- Clone https://github.com/theCrius/barotrauma-docker and follow the `readme.md` on how to install a modded server
- Add a server side mod, for example Riba Portable Items (https://steamcommunity.com/sharedfiles/filedetails/?id=2382545579)
- Add a client side mod, for example BetterHealthUI (https://steamcommunity.com/sharedfiles/filedetails/?id=2807158602)
- Be sure to add the relevant lines in `config_player.xml` as explained in the readme mentioned above
- Restart the server to be sure it picks up the mod list from the `config_player.xml`
- Try to connect and check from the server's list if the BetterHealthUI is listed.
- [OPTIONAL] Feel free to try with other mods checking which is actually requiring a server side installation and which not

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Linux

**Comment by evilfactory** [comment]
This happens because those mods don't have any XML content, so barotrauma assumes they are just submarine files or something similar and discards them, the solution is to add an empty XML content file to the filelist.xml.

**Comment by theCrius** [comment]
Thanks @evilfactory, I've reported this comment on Regalis11's issue. I don't think asking each mod's author to change their mods is feasible, however this insight might help the developers find a simple solution for the problem.

**Comment by Regalis11** [comment]
The issue was in the game itself: due to a bug that was introduced in the modding refactor, the clients would disable client-side-only mods when they join the server. We've fixed the issue in our priavte repo now, so the workaround of empty XML content should no longer be required once we get the fix out to the public version.

**Comment by theCrius** [comment]
Sorry, just asking clarification as what the "not planned" status means, because the obvious meaning cannot be right for this issue imho :)

**Comment by theCrius** [comment]
A sorry, my bad, I thought this was the issue on Regalis1's repository :)
