### ISSUE TITLE
Add support for loading scripts in the sub editor

### ISSUE THREAD

**Issue by notpeelz** [evilfactory/LuaCsForBarotrauma#95]
It could be useful to allow loading scripts while editing (not playtesting) in the subeditor, as some mods might want to patch/inject sub-editor specific code.
However this could possibly break existing mods that don't expect to be loaded in a sub editor environment.

**Comment by dakkhuza** [comment]
You can already do this by running `cl_reloadlua` while in the editor

**Comment by notpeelz** [comment]
That's a good workaround for now but it would be more user-friendly if scripts were loaded automatically in the sub editor.

**Comment by evilfactory** [comment]
Should be now more convenient to run stuff in the sub editor with the commit 069567c.

**Comment by notpeelz** [comment]
Looks like one of the `RegisterBarotrauma()` calls is wrong:
```
Lua/LuaUserData.lua:(23,4-60): Tried to register a type that doesn't exist: Barotrauma.CharacterEditorScreen.
```
The correct type is `Barotrauma.CharacterEditor.CharacterEditorScreen`

**Comment by evilfactory** [comment]
Fixed, weird how is it the only editor screen that has it's own namespace
