### ISSUE TITLE
Barotrauma does not open after copying over patch.

### ISSUE THREAD

**Issue by Meganium97** [evilfactory/LuaCsForBarotrauma#99]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I tried a manual install to get clientside lua on linux but it appears that it didnt work and now it doesn't open. I try to click start on steam and it syncs the cloud and then stops immediately.

### Reproduction steps

1. Install the patch for linux client
2. Try to start the game

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Linux

**Comment by evilfactory** [comment]
Can you try running the executable via the terminal? to see if any logs appear

**Comment by Meganium97** [comment]
`╰─λ ./Barotrauma
Error:
An assembly specified in the application dependencies manifest (Barotrauma.deps.json) was not found:
package: 'Sigil', version: '5.0.0'
path: 'lib/netstandard2.1/Sigil.dll'`

**Comment by evilfactory** [comment]
For a quick workaround, download the complete build zip from https://github.com/evilfactory/LuaCsForBarotrauma/releases/download/latest/luacsforbarotrauma_build_linux.zip and copy over the `Sigil.dll` file.

**Comment by Meganium97** [comment]
Where is that located and where should I be putting it?

**Comment by Meganium97** [comment]
Thanks for your help, it fixed the issue.

**Comment by evilfactory** [comment]
I'll keep the issue open until it's fixed without the workaround
